from __future__ import annotations

import argparse
import json
import math
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd


def _candidate_cols(columns) -> list[str]:
    cols = [c for c in columns if str(c).lower().startswith("c") and str(c)[1:].isdigit()]
    return sorted(cols, key=lambda x: int(str(x)[1:]))


def _train_history_only(train: pd.DataFrame, include_valid_history: bool = False) -> pd.DataFrame:
    if include_valid_history or "split" not in train.columns:
        return train
    split = train["split"]
    if split.dtype.kind in {"i", "u", "f"}:
        return train[split.astype(int) == 0].copy()
    normalized = split.astype(str).str.lower().str.strip()
    return train[normalized.isin(["0", "train", "training"])].copy()


def build_stats(train_path: Path, include_valid_history: bool = False):
    train = pd.read_csv(train_path)
    train = _train_history_only(train, include_valid_history=include_valid_history)
    src_col, dst_col = "src", "dst"
    if src_col not in train.columns or dst_col not in train.columns:
        raise ValueError(f"{train_path} must contain src,dst columns")
    if len(train) == 0:
        raise ValueError(f"No allowed history edges remain after split filtering: {train_path}")
    dst_pop = train[dst_col].value_counts().to_dict()
    src_degree = train[src_col].value_counts().to_dict()
    pair_count = train.groupby([src_col, dst_col], sort=False).size().to_dict()
    if "time" in train.columns:
        last_pair = train.groupby([src_col, dst_col], sort=False)["time"].max().to_dict()
        last_dst = train.groupby(dst_col, sort=False)["time"].max().to_dict()
        last_src = train.groupby(src_col, sort=False)["time"].max().to_dict()
    else:
        last_pair, last_dst, last_src = {}, {}, {}
    max_time = float(train["time"].max()) if "time" in train.columns else 0.0
    return dst_pop, src_degree, pair_count, last_pair, last_dst, last_src, max_time


def score_candidates(src: int, time_value: float, candidates: np.ndarray, dst_pop, src_degree, pair_count, last_pair, last_dst, last_src, max_time: float):
    scores = np.zeros(len(candidates), dtype=np.float64)
    src_deg = src_degree.get(src, 0)
    src_last = last_src.get(src, None)
    src_recency = 0.0 if src_last is None else 1.0 / math.log1p(max(1.0, time_value - float(src_last)))
    for i, dst in enumerate(candidates):
        dst = int(dst)
        pair = pair_count.get((src, dst), 0)
        pop = dst_pop.get(dst, 0)
        lp = last_pair.get((src, dst), None)
        ld = last_dst.get(dst, None)
        pair_recency = 0.0 if lp is None else 1.0 / math.log1p(max(1.0, time_value - float(lp)))
        dst_recency = 0.0 if ld is None else 1.0 / math.log1p(max(1.0, time_value - float(ld)))
        pair_share = pair / max(1, src_deg)
        # Candidate columns are usually generated by a retrieval model. Preserve
        # a small prior from that order while letting historical evidence rerank.
        candidate_prior = 1.0 / math.log2(i + 2.0)
        scores[i] = (
            3.4 * math.log1p(pair)
            + 1.15 * math.log1p(pop)
            + 2.2 * pair_recency
            + 0.45 * dst_recency
            + 0.25 * src_recency
            + 0.8 * pair_share
            + 0.15 * candidate_prior
        )
    return scores


def make_submission(
    data_dir: Path,
    output_dir: Path,
    chunk_size: int = 5000,
    json_mode: str = "sorted_ids",
    include_valid_history: bool = False,
):
    train_path = data_dir / "train.csv"
    test_path = data_dir / "test.csv"
    if not train_path.exists() or not test_path.exists():
        raise FileNotFoundError(f"Expected train.csv and test.csv under {data_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    dst_pop, src_degree, pair_count, last_pair, last_dst, last_src, max_time = build_stats(
        train_path,
        include_valid_history=include_valid_history,
    )

    header = pd.read_csv(test_path, nrows=0)
    cand_cols = _candidate_cols(header.columns)
    if not cand_cols:
        raise ValueError(f"No c1..c100 candidate columns found in {test_path}")
    rank_cols = ["query_id"] + [f"rank{i}" for i in range(1, len(cand_cols) + 1)]
    score_cols = ["query_id"] + cand_cols

    ranked_path = output_dir / "result_ranked.csv"
    scores_path = output_dir / "result_scores.csv"
    json_path = output_dir / "result.json"
    pred_path = output_dir / "predictions.csv"

    first_json = True
    query_offset = 0
    with ranked_path.open("w", encoding="utf-8", newline="") as fr, scores_path.open("w", encoding="utf-8", newline="") as fs, pred_path.open("w", encoding="utf-8", newline="") as fp, json_path.open("w", encoding="utf-8") as fj:
        fr.write(",".join(rank_cols) + "\n")
        fs.write(",".join(score_cols) + "\n")
        fp.write("candidate_id,query_id,candidate_rank,src,dst,time,score\n")
        fj.write("{\n")
        for chunk in pd.read_csv(test_path, chunksize=chunk_size):
            cands_mat = chunk[cand_cols].to_numpy(np.int64)
            srcs = chunk["src"].to_numpy(np.int64)
            times = chunk["time"].to_numpy(np.float64) if "time" in chunk.columns else np.zeros(len(chunk), dtype=np.float64)
            for local_i in range(len(chunk)):
                qid = query_offset + local_i
                cands = cands_mat[local_i]
                scores = score_candidates(int(srcs[local_i]), float(times[local_i]), cands, dst_pop, src_degree, pair_count, last_pair, last_dst, last_src, max_time)
                order = np.argsort(-scores)
                ranked = cands[order]
                fr.write(",".join([str(qid)] + [str(int(x)) for x in ranked]) + "\n")
                fs.write(",".join([str(qid)] + [f"{float(x):.8f}" for x in scores]) + "\n")
                for rank, (dst, score) in enumerate(zip(cands, scores), start=1):
                    fp.write(f"{qid}_{rank},{qid},{rank},{int(srcs[local_i])},{int(dst)},{float(times[local_i])},{float(score):.8f}\n")
                if json_mode == "sorted_ids":
                    json_value = [int(x) for x in ranked]
                elif json_mode == "ranks":
                    ranks = np.empty(len(cands), dtype=np.int64)
                    ranks[order] = np.arange(1, len(cands) + 1)
                    json_value = [int(x) for x in ranks]
                elif json_mode == "scores":
                    json_value = [float(f"{float(x):.8f}") for x in scores]
                else:
                    raise ValueError(f"Unknown json_mode: {json_mode}")
                if not first_json:
                    fj.write(",\n")
                first_json = False
                fj.write(f'  "{qid}": ' + json.dumps(json_value, ensure_ascii=False))
            query_offset += len(chunk)
        fj.write("\n}\n")

    zip_path = output_dir.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(json_path, arcname="result.json")
    return json_path, zip_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-root", type=str, default="data/official_raw")
    parser.add_argument("--dataset", type=str, default="dataset1", choices=["dataset1", "dataset2"])
    parser.add_argument("--output-root", type=str, default="outputs/track1_heuristic")
    parser.add_argument("--chunk-size", type=int, default=5000)
    parser.add_argument("--json-mode", type=str, default="sorted_ids", choices=["scores", "ranks", "sorted_ids"])
    parser.add_argument("--include-valid-history", action="store_true", help="Use split=1 edges as final test history. Disabled by default to avoid validation-label leakage.")
    args = parser.parse_args()
    data_dir = Path(args.data_root) / args.dataset
    output_dir = Path(args.output_root) / args.dataset
    result, z = make_submission(
        data_dir,
        output_dir,
        chunk_size=args.chunk_size,
        json_mode=args.json_mode,
        include_valid_history=args.include_valid_history,
    )
    print(f"wrote {result}")
    print(f"packaged {z}")


if __name__ == "__main__":
    main()
